version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=deploy_pipeline.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
